/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const SearchableUserProfile = IDL.Record({
  'principal' : IDL.Principal,
  'email' : IDL.Text,
  'lastName' : IDL.Text,
  'firstName' : IDL.Text,
});
export const Time = IDL.Int;
export const JobVacancy = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'postedAt' : Time,
  'description' : IDL.Text,
  'salaryRange' : IDL.Text,
  'requirements' : IDL.Vec(IDL.Text),
});
export const ApplicationStatus = IDL.Variant({
  'pending' : IDL.Null,
  'rejected' : IDL.Null,
  'reviewed' : IDL.Null,
  'accepted' : IDL.Null,
});
export const Application = IDL.Record({
  'id' : IDL.Nat,
  'status' : ApplicationStatus,
  'resume' : IDL.Opt(ExternalBlob),
  'appliedAt' : Time,
  'user' : IDL.Principal,
  'jobId' : IDL.Nat,
  'coverLetter' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'resume' : IDL.Opt(ExternalBlob),
  'email' : IDL.Text,
  'lastName' : IDL.Text,
  'firstName' : IDL.Text,
});
export const Message = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'sender' : IDL.Principal,
  'sentAt' : Time,
  'receiver' : IDL.Principal,
});
export const Post = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : Time,
  'author' : IDL.Principal,
  'image' : IDL.Opt(ExternalBlob),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'applyForJob' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Opt(ExternalBlob)],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'authorizedUserSearch' : IDL.Func(
      [IDL.Opt(IDL.Text)],
      [IDL.Vec(SearchableUserProfile)],
      ['query'],
    ),
  'createJobVacancy' : IDL.Func([JobVacancy], [IDL.Nat], []),
  'createPost' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
      [IDL.Nat],
      [],
    ),
  'deleteJobVacancy' : IDL.Func([IDL.Nat], [], []),
  'deletePost' : IDL.Func([IDL.Nat], [], []),
  'getAllApplications' : IDL.Func([], [IDL.Vec(Application)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getInbox' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getJobVacancies' : IDL.Func([], [IDL.Vec(JobVacancy)], ['query']),
  'getJobVacancy' : IDL.Func([IDL.Nat], [JobVacancy], ['query']),
  'getMyApplications' : IDL.Func([], [IDL.Vec(Application)], ['query']),
  'getPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getSentMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchJobVacancies' : IDL.Func(
      [IDL.Opt(IDL.Text)],
      [IDL.Vec(JobVacancy)],
      ['query'],
    ),
  'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Nat], []),
  'updateApplicationStatus' : IDL.Func([IDL.Nat, ApplicationStatus], [], []),
  'updateJobVacancy' : IDL.Func([IDL.Nat, JobVacancy], [], []),
  'updatePost' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const SearchableUserProfile = IDL.Record({
    'principal' : IDL.Principal,
    'email' : IDL.Text,
    'lastName' : IDL.Text,
    'firstName' : IDL.Text,
  });
  const Time = IDL.Int;
  const JobVacancy = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'postedAt' : Time,
    'description' : IDL.Text,
    'salaryRange' : IDL.Text,
    'requirements' : IDL.Vec(IDL.Text),
  });
  const ApplicationStatus = IDL.Variant({
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
    'reviewed' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const Application = IDL.Record({
    'id' : IDL.Nat,
    'status' : ApplicationStatus,
    'resume' : IDL.Opt(ExternalBlob),
    'appliedAt' : Time,
    'user' : IDL.Principal,
    'jobId' : IDL.Nat,
    'coverLetter' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'resume' : IDL.Opt(ExternalBlob),
    'email' : IDL.Text,
    'lastName' : IDL.Text,
    'firstName' : IDL.Text,
  });
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'sender' : IDL.Principal,
    'sentAt' : Time,
    'receiver' : IDL.Principal,
  });
  const Post = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : Time,
    'author' : IDL.Principal,
    'image' : IDL.Opt(ExternalBlob),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'applyForJob' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Opt(ExternalBlob)],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'authorizedUserSearch' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [IDL.Vec(SearchableUserProfile)],
        ['query'],
      ),
    'createJobVacancy' : IDL.Func([JobVacancy], [IDL.Nat], []),
    'createPost' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
        [IDL.Nat],
        [],
      ),
    'deleteJobVacancy' : IDL.Func([IDL.Nat], [], []),
    'deletePost' : IDL.Func([IDL.Nat], [], []),
    'getAllApplications' : IDL.Func([], [IDL.Vec(Application)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getInbox' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getJobVacancies' : IDL.Func([], [IDL.Vec(JobVacancy)], ['query']),
    'getJobVacancy' : IDL.Func([IDL.Nat], [JobVacancy], ['query']),
    'getMyApplications' : IDL.Func([], [IDL.Vec(Application)], ['query']),
    'getPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getSentMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchJobVacancies' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [IDL.Vec(JobVacancy)],
        ['query'],
      ),
    'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Nat], []),
    'updateApplicationStatus' : IDL.Func([IDL.Nat, ApplicationStatus], [], []),
    'updateJobVacancy' : IDL.Func([IDL.Nat, JobVacancy], [], []),
    'updatePost' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };