/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Application {
  'id' : bigint,
  'status' : ApplicationStatus,
  'resume' : [] | [ExternalBlob],
  'appliedAt' : Time,
  'user' : Principal,
  'jobId' : bigint,
  'coverLetter' : string,
}
export type ApplicationStatus = { 'pending' : null } |
  { 'rejected' : null } |
  { 'reviewed' : null } |
  { 'accepted' : null };
export type ExternalBlob = Uint8Array;
export interface JobVacancy {
  'id' : bigint,
  'title' : string,
  'postedAt' : Time,
  'description' : string,
  'salaryRange' : string,
  'requirements' : Array<string>,
}
export interface Message {
  'id' : bigint,
  'content' : string,
  'sender' : Principal,
  'sentAt' : Time,
  'receiver' : Principal,
}
export interface Post {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'createdAt' : Time,
  'author' : Principal,
  'image' : [] | [ExternalBlob],
}
export interface SearchableUserProfile {
  'principal' : Principal,
  'email' : string,
  'lastName' : string,
  'firstName' : string,
}
export type Time = bigint;
export interface UserProfile {
  'resume' : [] | [ExternalBlob],
  'email' : string,
  'lastName' : string,
  'firstName' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'applyForJob' : ActorMethod<[bigint, string, [] | [ExternalBlob]], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'authorizedUserSearch' : ActorMethod<
    [[] | [string]],
    Array<SearchableUserProfile>
  >,
  'createJobVacancy' : ActorMethod<[JobVacancy], bigint>,
  'createPost' : ActorMethod<[string, string, [] | [ExternalBlob]], bigint>,
  'deleteJobVacancy' : ActorMethod<[bigint], undefined>,
  'deletePost' : ActorMethod<[bigint], undefined>,
  'getAllApplications' : ActorMethod<[], Array<Application>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getInbox' : ActorMethod<[], Array<Message>>,
  'getJobVacancies' : ActorMethod<[], Array<JobVacancy>>,
  'getJobVacancy' : ActorMethod<[bigint], JobVacancy>,
  'getMyApplications' : ActorMethod<[], Array<Application>>,
  'getPosts' : ActorMethod<[], Array<Post>>,
  'getSentMessages' : ActorMethod<[], Array<Message>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchJobVacancies' : ActorMethod<[[] | [string]], Array<JobVacancy>>,
  'sendMessage' : ActorMethod<[Principal, string], bigint>,
  'updateApplicationStatus' : ActorMethod<
    [bigint, ApplicationStatus],
    undefined
  >,
  'updateJobVacancy' : ActorMethod<[bigint, JobVacancy], undefined>,
  'updatePost' : ActorMethod<
    [bigint, string, string, [] | [ExternalBlob]],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];